#include <Arduino.h>



String  index_html_0 =  "<!DOCTYPE html><head>    <meta charset=\"utf-8\">    <title>Glasses</title><meta charset=\"utf-8\">    <style>        * {            background-color: #49423d;            color: beige;        }        #header {            display: inline-block;            margin-left: 7%;            margin-right: 7%;            width: 86%;        }        #header p {            font-size: 5vw;            text-align: center;            margin: 0px;        }        #content {            display: inline-block;            margin-left: 7%;            margin-right: 7%;            margin-top: 15px;            width: 86%;            text-align: center;        }        #form textarea {            font-size: 6.5vw;        }        #form textarea:focus, input:focus {            outline: none;        }        #send {            margin-top: 5px;            width: 85vw;            font-size: 7vw;            background-color: beige;            color: #49423d;        }        .textareas {            margin-top: 2vh;        }        #buttons {            display: inline-block;            margin-left: 7%;            margin-right: 7%;            width: 86%;        }        #pages {            text-align: center;            font-size: 6vw;        }        #down {            background-color: beige;            color: #49423d;        }        #up {            background-color: beige;            color: #49423d;        }    </style></head><body>    <div id=\"header\">        <p>Intaractive glasses interface by Leo-Choo</p>    </div>    <div id=\"buttons\">        <form action=\"/\" method=\"POST\" id=\"pages\">            <input name=\"DOWN\" type=\"submit\" value=\"Назад\" id=\"down\" style=\"font-size: 7vw; float: left; width: 30vw;\">            <p style=\"display: inline;\">";
String  index_html_1 =  "</p>            <input  name=\"UP\" type=\"submit\" value=\"Вперёд\" id=\"up\" style=\"font-size: 7vw; float: right; width: 30vw;\">        </form>    </div><br>    <div id=\"content\">        <form id=\"form\" action=\"/\" method=\"POST\">            <input type=\"submit\" value=\"Отправить\" id=\"send\"><br>            <textarea name=\"list0\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 0\" maxlength=\"84\" class=\"textareas\" id=\"text0\">";
String list0 =  "</textarea><br>            <textarea name=\"list1\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 1\" maxlength=\"84\" class=\"textareas\" id=\"text1\">";
String list1 =  "</textarea><br>            <textarea name=\"list2\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 2\" maxlength=\"84\" class=\"textareas\" id=\"text2\">";
String list2 =  "</textarea><br>            <textarea name=\"list3\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 3\" maxlength=\"84\" class=\"textareas\" id=\"text3\">";
String list3 =  "</textarea><br>            <textarea name=\"list4\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 4\" maxlength=\"84\" class=\"textareas\" id=\"text4\">";
String list4 =  "</textarea><br>            <textarea name=\"list5\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 5\" maxlength=\"84\" class=\"textareas\" id=\"text5\">";
String list5 =  "</textarea><br>            <textarea name=\"list6\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 6\" maxlength=\"84\" class=\"textareas\" id=\"text6\">";
String list6 =  "</textarea><br>            <textarea name=\"list7\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 7\" maxlength=\"84\" class=\"textareas\" id=\"text7\">";
String list7 =  "</textarea><br>            <textarea name=\"list8\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 8\" maxlength=\"84\" class=\"textareas\" id=\"text8\">";
String list8 =  "</textarea><br>            <textarea name=\"list9\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 9\" maxlength=\"84\" class=\"textareas\" id=\"text9\">";
String list9 =  "</textarea><br>            <textarea name=\"list10\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 10\" maxlength=\"84\" class=\"textareas\" id=\"text10\">";
String list10 =  "</textarea><br>            <textarea name=\"list11\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 11\" maxlength=\"84\" class=\"textareas\" id=\"text11\">";
String list11 =  "</textarea><br>            <textarea name=\"list12\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 12\" maxlength=\"84\" class=\"textareas\" id=\"text12\">";
String list12 =  "</textarea><br>            <textarea name=\"list13\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 13\" maxlength=\"84\" class=\"textareas\" id=\"text13\">";
String list13 =  "</textarea><br>            <textarea name=\"list14\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 14\" maxlength=\"84\" class=\"textareas\" id=\"text14\">";
String list14 =  "</textarea><br>            <textarea name=\"list15\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 15\" maxlength=\"84\" class=\"textareas\" id=\"text15\">";
String list15 =  "</textarea><br>            <textarea name=\"list16\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 16\" maxlength=\"84\" class=\"textareas\" id=\"text16\">";
String list16 =  "</textarea><br>            <textarea name=\"list17\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 17\" maxlength=\"84\" class=\"textareas\" id=\"text17\">";
String list17 =  "</textarea><br>            <textarea name=\"list18\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 18\" maxlength=\"84\" class=\"textareas\" id=\"text18\">";
String list18 =  "</textarea><br>            <textarea name=\"list19\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 19\" maxlength=\"84\" class=\"textareas\" id=\"text19\">";
String list19 =  "</textarea><br>            <textarea name=\"list20\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 20\" maxlength=\"84\" class=\"textareas\" id=\"text20\">";
String list20 =  "</textarea><br>            <textarea name=\"list21\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 21\" maxlength=\"84\" class=\"textareas\" id=\"text21\">";
String list21 =  "</textarea><br>            <textarea name=\"list22\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 22\" maxlength=\"84\" class=\"textareas\" id=\"text22\">";
String list22 =  "</textarea><br>            <textarea name=\"list23\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 23\" maxlength=\"84\" class=\"textareas\" id=\"text23\">";
String list23 =  "</textarea><br>            <textarea name=\"list24\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 24\" maxlength=\"84\" class=\"textareas\" id=\"text24\">";
String list24 =  "</textarea><br>            <textarea name=\"list25\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 25\" maxlength=\"84\" class=\"textareas\" id=\"text25\">";
String list25 =  "</textarea><br>            <textarea name=\"list26\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 26\" maxlength=\"84\" class=\"textareas\" id=\"text26\">";
String list26 =  "</textarea><br>            <textarea name=\"list27\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 27\" maxlength=\"84\" class=\"textareas\" id=\"text27\">";
String list27 =  "</textarea><br>            <textarea name=\"list28\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 28\" maxlength=\"84\" class=\"textareas\" id=\"text28\">";
String list28 =  "</textarea><br>            <textarea name=\"list29\" cols=\"21\" rows=\"4\" placeholder=\"Какой-то текст на станице 29\" maxlength=\"84\" class=\"textareas\" id=\"text29\">";
String list29 =  "</textarea><br>        </form>    </div></body></html";